apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify
  labels:
    app: emojify
    prometheus: scrappable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify
  template:
    metadata:
      labels:
        app: emojify
        prometheus: scrappable
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        - name: regcred
      containers:
        - name: emojify
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: emojify-secrets
                  key: SECRET_KEY
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
