apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: default
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack.default:3100
        isDefault: true
        version: 1
        editable: true
