apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:4.0
          ports:
            - containerPort: 9000
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: "${{ secrets.SECRET_KEY }}"
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "$(echo -n 'admin_password' | sha256sum | awk '{print $1}')"
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: "http://graylog:9000/"
            - name: MONGO_URI
              value: "mongodb://mongodb.default.svc.cluster.local:27017/graylog"
