# Конфигурация для установки Prometheus с помощью Helm
alertmanager:
  enabled: true
  service:
    type: LoadBalancer

server:
  enabled: true
  service:
    type: LoadBalancer
    port: 80

pushgateway:
  enabled: false

# Ресурсы для сервера Prometheus
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Настройки для сбора метрик с приложения emojify
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'emojify'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: emojify

# Дополнительные настройки для компонентов Prometheus
nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: true

alertmanager:
  enabled: true
